name: All Checks
on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    if: ${{ github.event_name != 'pull_request' || !github.event.pull_request.isDraft }}
    uses: ./.github/workflows/auto-format.yaml
    secrets: inherit
  ci-tests:
    if: ${{ github.event_name != 'pull_request' || !github.event.pull_request.isDraft }}
    uses: ./.github/workflows/ci-tests.yaml
    secrets: inherit
  docs:
    if: ${{ github.event_name != 'pull_request' || !github.event.pull_request.isDraft }}
    uses: ./.github/workflows/docs.yaml
    secrets: inherit
    needs: ci-tests
