name: PR Check
on:
  pull_request:
    types: [ready_for_review, synchronize]
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    uses: ./.github/workflows/auto-format.yaml
    secrets: inherit
  docs:
    uses: ./.github/workflows/docs.yaml
    secrets: inherit
