name: Report Tests
on:
  workflow_run:
    workflows: ['CI Tests']
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  report:
    permissions:
      contents: read
      actions: read
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: /report-(.*).xml/
          name: Test results $1
          path: '*.xml'
          reporter: java-junit